export const SITE = {
  website: "https://ivaylogb.github.io/",
  author: "Ivaylo Bahtchevanov",
  profile: "https://github.com/ivaylogb",
  desc: "Production engineering for LLM-mediated systems.",
  title: "Ivaylo Bahtchevanov",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 10,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "Edit page",
    url: "",
  },
  dynamicOgImage: false,
  dir: "ltr",
  lang: "en",
  timezone: "America/Los_Angeles",
} as const;
